spring:
  datasource:
    url: jdbc:h2:mem:recipesdbs
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        search:
          backend:
            type: lucene
            lucene_version: LATEST
            directory:
              type: local-filesystem
              root: ./lucene-index
  main:
    allow-bean-definition-overriding: true


external:
  recipes:
    url: https://dummyjson.com/recipes

resilience4j:
  circuitbreaker:
    instances:
      recipeService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      recipeService:
        maxAttempts: 2
        waitDuration: 1s
